### ISSUE TITLE
[BUG]: ZL EQ NOt passing audio in mono track (universal audio LUNA DAW)

### ISSUE THREAD

**Issue by SpeedFingers** [ZL-Audio/ZLEqualizer#138]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format: 0.4.5

- A clear and concise description of what the bug is:
 
1.-when i insert the plugin in a mono track channel, the plugin loads perfecly,but it mutes the audio. this do not happend on stereo channels. It used to work fine.  Abaut luna ( luna has no mono to stereo channels) MISO channels i believe they are called. Mono and stereo plugins exclusively. but in old releases just worked fine.

UAD LUNA its a Free Daw, so mayby you can test this directly.

2.- when i tried to solo a frequency, the GUI focus on the solo it is out of place to the right. This happend since version  0.4.3. it happends in LUNA AND STUDIO ONE

- A clear and concise description of what you expected to happen:expected to work fine


Thanks for the great work that you are doing. you plugin its Fantastic. i love it.

keep the good work.

Cheers. 

Mandy From Chile.
```

### Additional information

```markdown
- Operating system (& version if applicable):WINDOWS 10
- Hardware (CPU & GPU if applicable): INtel core i7, 16 Gb Ram
- DAW:Universal Audio Luna and studio one 6
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
Thanks for reporting. I will look into those issues shortly. Hopefully, I can fix them before the beta release of 0.5.0.

**Comment by zsliu98** [comment]
As I do not want to install UAD-related software on my Windows, I test it on macOS:

- the plugin can process mono track. However, if it is a mono track with a stereo side chain, it may mute the signal. I will try to fix it soon.
- I can reproduce the second issue. Sometimes the solo focus is out of place. I will try to fix it soon.

**Comment by zsliu98** [comment]
Those two issues should get fixed in 59efa3230b5b130b67dff5b9d271af2ae1742d2e and 3a8c50038e146a2681c250c7366a26bd3dd23413.

Would you like to try the installer in the attachment?

[ZL Equalizer-0.4.5-Windows-Software.exe.zip](https://github.com/user-attachments/files/18171628/ZL.Equalizer-0.4.5-Windows-Software.exe.zip)

**Comment by SpeedFingers** [comment]
Thanks!. I'll try it and let you know. Cheers

**Comment by SpeedFingers** [comment]
Hey..i tried it. the solo focus worked. the not passing audio in mono problem is still there. Thanks.

**Comment by zsliu98** [comment]
Interesting. I will debug the plugin in Pro Tools mono track tonight and see if I can find the problem.

**Comment by SpeedFingers** [comment]
thanks. if you can Try luna is free for mac also. and you can use it without any UAD hardware. maybe you can get a profound insight from it. 
thanks for your efforts man. it amazing work!

**Comment by zsliu98** [comment]
OK, I finally managed to install the LUNA DAW on my Windows. On my local computer, ZL Equalizer 0.5.0 can successfully process a mono-track. However, as I am new to LUNA, I may interpret it incorrectly. Here is what I get (the Untitled track is created from a mono WAV file):

<img width="953" alt="Screenshot 2024-12-18 at 07 55 30" src="https://github.com/user-attachments/assets/0c887f28-1075-4061-8596-d4c65657ea1a" />

Can you see the spectrum when you load it on a mono-track? Does it still mute the signal?

**Comment by SpeedFingers** [comment]
Hi. It seems that you got it. I can not see the spectrum when i inserted ZL in a mo l track it mutes. No spectrum.

**Comment by zsliu98** [comment]
The only difference I can see is that I am on Windows 11 and you are on Windows 10. But I don't think it matters. As I cannot reproduce the error, I may not be able to fix it. I will leave this issue open for a while to see if someone else encounters the same problem.

**Comment by SpeedFingers** [comment]
Hi. Just to clarify... asa workaround in luna i drag mono tracks to stereo channel and that works. (Luna can process mono source in a stereo track). Just to make sure maybe that is what happened in your case? key commands for crating tracks are the same as protoos. Ctr+Shift+n.
Another difference is that yesterday i tried version 0.45 that you post me. not 0.5.

i do not know,  still have hope :)

**Comment by zsliu98** [comment]
Yes, I create a mono track and drag a mono WAV file onto it. Then I put ZL Equalizer on it and it works fine. I am using LUNA v1.8.0 on Windows 11. As you can see from the screenshot, the `PAN` shows as a single `C`, which *may* indicate a mono track?

FYI 0.5.0 Pre-Release is here: https://github.com/ZL-Audio/ZLEqualizer/releases/tag/0.5.0. But I don't think it can solve your issue.

___

Interesting. I create a stereo track in the same project and I cannot load ZL Equalizer onto it. Probably because ZL Equalizer requires the main input and the main output to be the same channel layout. I am not sure whether it is your case.

**Comment by SpeedFingers** [comment]
I can load it into mono and stereo tracks. Works fine here.

**Comment by zsliu98** [comment]
Thanks for working out this issue with me. I guess the version number needs to be updated so that LUNA can see some channel configuration changes there. I am closing this issue now.
