### ISSUE TITLE
Freezes/Crashes Reason 12 (Windows 10)

### ISSUE THREAD

**Issue by spfeffects** [ZL-Audio/ZLEqualizer#33]
It worked for the first time I used it but after that any time I would add a band or manipulate it in any way the plugin itself would freeze and then Reason would freeze causing me to have to "end task" in windows.

Reason 12, Windows 10

**Comment by zsliu98** [comment]
I have just released the version 0.1.14. Hopefully, this release will fix this issue.

**Comment by spfeffects** [comment]
thanks! It works much better now! I did still get it to freeze up eventually.
I will try using it and see if I can figure out what triggers it to get you a better report.

**Comment by spfeffects** [comment]
found it! it seems to freeze up after changing the dynamic threshold to Relative.

**Comment by zsliu98** [comment]
> found it! it seems to freeze up after changing the dynamic threshold to Relative.

Got it! Thanks for narrowing down the bug! I will look into it when I have time.

**Comment by zsliu98** [comment]
> found it! it seems to freeze up after changing the dynamic threshold to Relative.

It is caused by a small typo (introduced in 0.1.14). I have just released a quick fix in 0.1.16. Hopefully, it will solve this issue.

**Comment by spfeffects** [comment]
It seems to work perfectly now! thank you very much for this plugin, and for all of the hard work put into debugging it, I really think it's going to become one of my most used plugins! I will let you know if any more issues come up and If I can do anything more to help with debugging, please let me know. Thank you again.
